apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: celonis
  namespace: "celonis"
  labels:
    app.kubernetes.io/name: celonis
    app.kubernetes.io/instance: celonis
