{{- if not .Values.celonis.existingApiKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celonis.fullname" . }}-api-key
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "celonis.labels" . | nindent 4 }}
type: Opaque
data:
  celonis-api-key: {{ .Values.celonis.apiKey | b64enc | quote }}
{{- end }}