{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.selfSigned }}
{{- $hostnames := list .Values.ingress.hostname }}
{{- range .Values.ingress.extraHosts }}
  {{- $hostnames = append $hostnames .name }}
{{- end }}
{{- $ca := genCA "celonis-ca" 365 }}
{{- $cert := genSignedCert (index $hostnames 0) nil $hostnames 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celonis.fullname" . }}-tls
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: celonis
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}