annotations:
  licenses: MIT
apiVersion: v2
appVersion: 1.0.1
version: 0.1.1
name: celonis-challenge
description: Celonis Platform Engineering Challenge
home: https://github.com/joeyomi/celonis-challenge
icon: https://en.m.wikipedia.org/wiki/File:Celonis_Logo.png
maintainers:
  - name: joeyomi
    email: joseph.oyomi11@gmail.com
    url: https://github.com/joeyomi/
sources:
  - https://github.com/joeyomi/celonis-challenge
keywords:
  - celonis
  - challenge
  - platform-engineering-challenge
