name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "charts/**"
      - ".github/**"
      - "manifests"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: java
