name: Checkov Lint

on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12.2500.0
        continue-on-error: true
        with:
          quiet: true
